# Used for displaying playerheads in chat.
# This is the default font that comes with the plugin
# %chatty_playerhead% will be replaced with the playerhead of the player who sent the message
# Please note: This is not the most performance friendly feature so use the placeholder sparingly.
playerHeadFont: "minecraft:chatty_heads"

# Keep in mind this needs to also be enabled in your [server.properties] file
# It will warn all your players when they first join
# that the server can read all their messages before they are sent.
# Chatty does not do anything with it outside the [ChatPreview.kt] file.
#This feature requires ProtocolLib 5.0.0 or higher.
chat:
  bypassFormatPermission: "chatty.chat.bypassformat"
  commandSpyFormat: "<gold>%chatty_player_displayname%</gold><yellow>: "
  chatPreview:
    enabled: false
    includeFormatInPreview: true
  allowedTags: # Available formats are:
    - BOLD                    # [TEXTCOLOR, HEXCOLOR, GRADIENT, RAINBOW, UNDERLINE, STRIKETHROUGH, BOLD, ITALIC, OBFUSCATED]
    - STRIKETHROUGH           # [HOVER, CLICK, FONT, SPACES, INSERTION, RESET, TRANSITION, KEYBIND, TRANSLATABLE]
    - UNDERLINE               # https://docs.adventure.kyori.net/minimessage/format.html
    - ITALIC
    - TEXTCOLOR
    - HEXCOLOR
    - RAINBOW
    - GRADIENT


privateMessages:
  enabled: true
  proxy: true                       # Not currently supported
  messageReplyTime: 5m              # t: Ticks, s: Seconds, m: Minutes, h: Hours, d: Days, w: Weeks, mo: Months
  messageSendFormat: "<gold>You -> %chatty_player_displayname%: "
  messageReceiveFormat: "<gold>%chatty_player_displayname% -> You: "
  messageSendSound: ""              # Empty for no sound
  messageReceiveSound: ""           # Empty for no sound

book:
  useDisplayNameForAuthor: false
  bypassFormatPermission: "chatty.chat.bypassformat"
  allowedTags: # Available formats are:
    - BOLD                    # [TEXTCOLOR, HEXCOLOR, GRADIENT, RAINBOW, UNDERLINE, STRIKETHROUGH, BOLD, ITALIC, OBFUSCATED]
    - STRIKETHROUGH           # [HOVER, CLICK, FONT, SPACES, INSERTION, RESET, TRANSITION, KEYBIND, TRANSLATABLE]
    - UNDERLINE               # https://docs.adventure.kyori.net/minimessage/format.html
    - ITALIC
    - OBFUSCATED
    - TEXTCOLOR
    - HEXCOLOR
    - RAINBOW
    - GRADIENT

sign:
  bypassFormatPermission: "chatty.chat.bypassformat"
  allowedTags: # Available formats are:
    - BOLD                    # [TEXTCOLOR, HEXCOLOR, GRADIENT, RAINBOW, UNDERLINE, STRIKETHROUGH, BOLD, ITALIC, OBFUSCATED]
    - STRIKETHROUGH           # [HOVER, CLICK, FONT, SPACES, INSERTION, RESET, TRANSITION, KEYBIND, TRANSLATABLE]
    - UNDERLINE               # https://docs.adventure.kyori.net/minimessage/format.html
    - ITALIC
    - OBFUSCATED
    - TEXTCOLOR
    - HEXCOLOR
    - RAINBOW
    - GRADIENT

nicknames:
  permission: "chatty.nickname"
  nickOtherPermission: "chatty.nickname.other"
  bypassFormatPermission: "chatty.nickname.bypassformat" #Permission to bypass all format checks
  maxLength: 32
  countTagsInLength: false    # Should [maxLength] take tags into account?
  nickNameOtherPrefix: '@'    # Prefix to specify you wanna nickname another player: [/chatty nickname @player nickname]
  allowedTags:                # Available formats are:
    - BOLD                    # [TEXTCOLOR, HEXCOLOR, GRADIENT, RAINBOW, UNDERLINE, STRIKETHROUGH, BOLD, ITALIC, OBFUSCATED]
    - STRIKETHROUGH           # [HOVER, CLICK, FONT, SPACES, INSERTION, RESET, TRANSITION, KEYBIND, TRANSLATABLE]
    - UNDERLINE               # https://docs.adventure.kyori.net/minimessage/format.html
    - ITALIC
    - OBFUSCATED
    - TEXTCOLOR
    - HEXCOLOR
    - RAINBOW
    - GRADIENT

join:
  enabled: true
  firstJoin:
    enabled: true

leave:
  enabled: true

proxy:
  enableProxySwitchMessages: false
  discordSrvChannelID: "Global"

ping:
  enabledChannels:          # channelIds to enable pings for
    - "global"              # "all" or "*" for all channels
  pingVolume: 1.0
  pingPitch: 1.0
  pingPrefix: '@'
  clickToReply: true
  pingReceiveFormat: "<gold><b>"  # Default format the ping-message is marked with for pinged
  pingSendFormat: "<i>"     # Default format the ping-message is marked with for sender
  defaultPingSound: "block.amethyst_block.place"
  alternativePingSounds:    # "all" to let people choose any sound
    - "block.stone.break"
    - "block.grass.place"


channels:
  global:
    channelType: GLOBAL       # GLOBAL, LOCAL, PRIVATE (Currently does nothing), PERMISSION
    isDefaultChannel: true
    proxy: true
    discordsrv: true
    format: ":survival: %luckperms_prefix%%%chatty_player_displayname%: "
    channelAliases:         # Shortcut commandalias to switch
      - "g"

  # %chatty_player_head% will be replaced with the playerhead of the player who sent the message
  # Keep in mind it is performance heavy so use sparingly.
  # Format of the message itself. Can change color and font for example
  playerhead:
    channelType: GLOBAL
    permission: "chatty.channel.playerhead"
    isDefaultChannel: false
    proxy: true
    discordsrv: true
    format: "%chatty_player_head% %luckperms_prefix% %%chatty_player_displayname%: "
    channelAliases:
      - "head"

  local:
    channelType: RADIUS
    isDefaultChannel: false
    format: "<yellow>[Local] %%chatty_player_displayname%:<yellow> "
    channelRadius: 500
    channelAliases:
      - "l"

  staff:
    channelType: PERMISSION
    permission: "chatty.channel.staff"
    requireEffectivePermission: false
    isDefaultChannel: false
    isStaffChannel: true
    format: "<red>[Staff] %%chatty_player_displayname%:<red> "
    channelAliases:
      - "a"
