name: chatty
version: ${plugin_version}
author: boy0000
main: com.mineinabyss.chatty.ChattyPlugin
api-version: 1.18
depend: [ Geary ]
softdepend: [ BondrewdLikesHisEmotes, PlaceholderAPI, DiscordSRV ]
description: TODO

commands:
  chatty:
