# Used for displaying playerheads in chat.
# This is the default font that comes with the plugin
# %chatty_playerhead% will be replaced with the playerhead of the player who sent the message
# Please note: This is not the most performance friendly feature so use the placeholder sparingly.
playerHeadFont: "minecraft:chatty_heads"
useChattyCommandPrefix: true

join:
  enabled: true
  firstJoin:
    enabled: true

leave:
  enabled: true

ping:
  enabledChannels: # "all" for all channels
    - "global"
  defaultPingSound: "block.amethyst_block.place"
  alternativePingSounds: # "all" to let people choose any sound
    - "block.stone.break"
    - "block.grass.place"
  pingVolume: 1.0
  pingPitch: 1.0
  pingPrefix: "@"
  clickToReply: true
  pingReceiveFormat: "<b>"
  pingSendFormat: "<i>"


channels:
  global:
    channelType: GLOBAL
    isDefaultChannel: true
    format:
      usePlayerDisplayName: true
      prefix: ":survival:"
      suffix: ": "
      messageFormat: ""
    channelAliases:
      - "g"

  playerhead:
    channelType: GLOBAL
    isDefaultChannel: true
    format:
      usePlayerDisplayName: true
      prefix: "%chatty_player_head%"
      suffix: ": "
      messageFormat: ""
    channelAliases:
      - "head"

  local:
    channelType: RADIUS
    isDefaultChannel: false
    format:
      usePlayerDisplayName: true
      prefix: "<yellow>[Local]"
      suffix: ": "
      messageFormat: "<yellow>"
    channelRadius: 500
    channelAliases:
      - "l"

  staff:
    channelType: PERMISSION
    permission: "chatty.channel.staff"
    requireEffectivePermission: false
    isDefaultChannel: false
    format:
      usePlayerDisplayName: true
      prefix: "<red>[Staff]"
      suffix: ": "
      messageFormat: "<red>"
    channelAliases:
      - "s"

messages:
  toggledPingSound: "Ping sound is now <i>%chatty_player_ping_toggle%</i>."
  changedPingSound: "Ping sound set to <i>%chatty_player_ping_sound%</i>"
  invalidPingSound: "<red>You must specify a valid sound to play."
  availableChannels: "<gold>Available channels are:<newline><yellow>%chatty_available_channels%"
  channelChanged: "<red>You have changed to channel <yellow>%chatty_player_channel%<red>."
  noChannelWithName: "No channel by this name exists."
  missingChannelPermission: "You do not have permission to join this channel."
  emptyChannelMessage: "<red>There is no-one to read your message"
  firstJoinMessage: "<gradient:#058330:#ff9200>Welcome %player_name% to %server_name%</gradient>"
  joinMessage: "<green>%player_name%<white> has joined the server."
  leaveMessage: "<red>%player_name%<white> has left the server."
  nickNameChanged: "Nickname set to <white><i>%player_displayname%</i></white>."
  configReloaded: "<green>Chatty config reloaded."
