# Used for displaying playerheads in chat.
# This is the default font that comes with the plugin
# %chatty_playerhead% will be replaced with the playerhead of the player who sent the message
playerHeadFont: "minecraft:chatty_heads"
useChattyCommandPrefix: true

join:
  enabled: true
  firstJoin:
    enabled: true

leave:
  enabled: true

ping:
  enabledChannels: # "all" for all channels
    - "global"
  defaultPingSound: "block.amethyst_block.place"
  alternativePingSounds: # "all" to let people choose any sound
    - "block.stone.break"
    - "block.grass.place"
  pingVolume: 1.0
  pingPitch: 1.0
  pingPrefix: "@"
  clickToReply: true
  pingReceiveFormat: "<b>"
  pingSendFormat: "<i>"


channels:
  - channelName: "global"
    channelType: GLOBAL
    isDefaultChannel: true
    format:
      usePlayerDisplayName: true
      prefix: ":survival:"
      suffix: ": "
      messageFormat: ""
    channelAliases:
      - "g"

  - channelName: "playerhead"
      channelType: GLOBAL
      isDefaultChannel: true
      format:
        usePlayerDisplayName: true
        prefix: "%chatty_playerhead% "
        suffix: ": "
        messageFormat: ""
      channelAliases:
        - "head"

  - channelName: "local"
    channelType: RADIUS
    isDefaultChannel: false
    format:
      usePlayerDisplayName: true
      prefix: "<yellow>[Local]"
      suffix: ": "
      messageFormat: "<yellow>"
    channelRadius: 500
    channelAliases:
      - "l"

  - channelName: "staff"
    channelType: PERMISSION
    permission: "chatty.channel.staff"
    requireEffectivePermission: false
    isDefaultChannel: false
    format:
      usePlayerDisplayName: true
      prefix: "<red>[Staff]"
      suffix: ": "
      messageFormat: "<red>"
    channelAliases:
      - "s"

messages:
  changedPingSound: "<green>You have changed the ping sound to <yellow>%sound%<green>."
  noSoundError: "<red>You must specify a valid sound to play"
  channelChangedMessage: "<red>You have changed to channel <yellow>%chatty_channel%<red>."
  emptyChannelMessage: "<red>There is no-one to read your message"
  firstJoinMessage: "<gradient:#058330:#ff9200>Welcome %player_name% to %server_name%</gradient>"
  joinMessage: "<green>%player_name%<white> has joined the server."
  leaveMessage: "<red>%player_name%<white> has left the server."
