useChattyCommandPrefix: true
channelChangedMessage: "<red>You have changed to channel <yellow>%chatty_channel%<red>."
join:
  enabled: true
  message: "<green>%player_name%<white> has joined the server."
  firstJoin:
    enabled: true
    message: "<gradient:#058330:#ff9200>Welcome %player_name% to %server_name%</gradient>"

leave:
  enabled: true
  message: "<green>%player_name%<white> has left the server."

ping:
  enabledChannels: # "all" for all channels
    - "global"
  defaultPingSound: "block.amethyst_block.place"
  alternativePingSounds: # "all" to let people choose any sound
    - "block.stone.break"
    - "block.grass.place"
  pingVolume: 1.0
  pingPitch: 1.0
  pingPrefix: "@"
  clickToReply: true
  pingFormat: "<b>"


channels:
  - channelName: "global"
    channelType: GLOBAL
    isDefaultChannel: true

    format:
      usePlayerDisplayName: true
      prefix: ":survival:"
      suffix: ": "
      messageFormat: ""
    channelAliases:
      - "g"

  - channelName: "local"
    channelType: RADIUS
    isDefaultChannel: false
    format:
      usePlayerDisplayName: true
      prefix: "<yellow>[Local]"
      suffix: ": "
      messageFormat: "<yellow>"
    channelRadius: 500
    emptyChannelMessage: "<red>There is no-one to read your message"
    channelAliases:
      - "l"

  - channelName: "staff"
    channelType: PERMISSION
    permission: "chatty.channel.staff"
    requireEffectivePermission: false
    isDefaultChannel: false
    format:
      usePlayerDisplayName: true
      prefix: "<red>[Staff]"
      suffix: ": "
      messageFormat: "<red>"
    emptyChannelMessage: "<red>There is no-one to read your message"
    channelAliases:
      - "s"
