# TODO fill in this file
name: TODO
version: ${plugin_version}
author: TODO
main: com.mineinabyss.example.ExamplePlugin
api-version: 1.18
#depend:
#softdepend:
description: TODO

commands:
  example:
    aliases: [ example, ex ]
    description: An example command
