[versions]
velocity = "3.4.0-SNAPSHOT"
discordsrv = "1.30.4"
placeholderapi = "2.11.7"

[libraries]
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
discordsrv = { module = "com.discordsrv:discordsrv", version.ref = "discordsrv" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
