name: Java CI with Gradle

on:
  push:
    branches:
      - master
      - backport_master
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: gradle build

      - name: Upload Velocity build
        uses: actions/upload-artifact@v1
        with:
          name: velocity-build
          path: chatty-velocity/build/libs

      - name: Upload Paper build
        uses: actions/upload-artifact@v1
        with:
          name: paper-build
          path: chatty-paper/build/libs
